### ISSUE TITLE
Book Suggestion: Code Complete

### ISSUE THREAD

**Issue by Will-Lo** [Roar1827/Ryan-Clements#1]
The reason I think you would benefit from this book is-that the book, although a bit dated, speaks about best software practices and infrastructure that are still used today. Some people say that this book is a must read for everyone who's dedicated to making excellent software, so I think you'll enjoy it.

A very quick summary of the book's points are <a href = "http://programmers.stackexchange.com/questions/2777/what-are-the-key-points-of-code-complete"> here.

**Comment by Roar1827** [comment]
Thanks for the suggestion! I have added it to my list.
